### ISSUE TITLE
Great Job! it could be possible without SD?

### ISSUE THREAD

**Issue by sommo** [G6EJD/ESP-Web-Server-v2#1]
Hi G6EJD,
great great Job!
I don't know how to reach you so i opened an issue ?!
i tested your sketch and also without the SD module works (with some html problem/warning messages) but it works (i can trigger the relay and read temperature, moving in html folder).
I don't have the SD shield, and i love your work. i'm not so able to coding, could it possible to have a version without the integration of the SD module?
i could contribute with a paypal donation :)
and a question, why is the SD so "necessary" in that project or helpful? maybe i have to think to buy that module..
thank you, and happy new year! :D

**Comment by sommo** [comment]
another question, while i'm studying your project, how can i read the real state of the realy_pin? for now i understand that forcing on or off, i obtain the status, but if i only want to read the relay status, how could i do? switching or curling the url /RELAY_on or /RELAY_off it switch the relay's status...

**Comment by sommo** [comment]
maybe thanks to SD card i could store that information, store the relay's status and then read from that... sorry for spamming... :P but i'm really interesting to do it well, i've ordered an SD shield in the meanwhile :D

**Comment by sommo** [comment]
again... i also see that the board correctly connect to an ssid network but it also work as AccessPoint, i could stop that, i no need that it could also be reachable by is own created network.
Thank you again, and as i said, Happy New year! :)

**Comment by G6EJD** [comment]
Yes, doing all this without an SD Card is possible. But for larger web sites it's very hard to track all the HTML and the SD Card enables a web site to be developed and then copied to the SD Card without having to 'hand-code' each HTML page. 
You could only read the actual Relay pin state by using another input connected to the Relay pin and then report that, otherwise you can read the register state and report that. In the latter case just because the pin has been set HIGH does not mean the relay has been switched on. In most cases it is sufficient to read the register state for the relay control and report that.
I have designed you a new version that does not use the SD Card and with a home page and a menu to enable functions to be selected, including two unused sections for expansion if required. I think that closes these issues.
How does $15 sound as a contribution and I will continue to amend it to your needs within reason. contact and PayPal me at d.l.bird@sky.com
